name: qQuests
main: me.quaz3l.qQuests.qQuests
version: 2003
description: A overly customizable quests plugin.
softdepend: [Vault, Citizens]
commands:
  QQUESTS:
    description: Main Command To Use qQuests
    aliases:
    - q
    - qu
    - quest
    - quests
    - qquest
    - qquests
permissions:
    qquests.*:
        description: Gives all qQuest permissions
        default: op
        children:
            qquests.give: true
            qquests.give.specific: true
            qquests.info: true
            qquests.tasks: true
            qquests.drop: true
            qquests.done: true
            qquests.reload: true
            qquests.admin: true
    qquests.give:
        description: Lets players randomly get a visible quest
        default: true
        children:
            qquests.give.sign: true
    qquests.give.specific:
        description: Lets players specify a quest they want
        default: op
    qquests.info:
        description: Lets players see info on there quest
        default: true
        children:
            qquests.info.sign: true
    qquests.tasks:
        description: Lets players see there tasks
        default: true
        children:
            qquests.tasks.sign: true
    qquests.drop:
        description: Enables players to drop quests
        default: true
        children:
            qquests.drop.sign: true
    qquests.done:
        description: Lets players finish a quest
        default: true
        children:
            qquests.done.sign: true
    qquests.list:
        description: Lists All Available Quests
        default: true
        children:
            qquests.list.sign: true
        qquests.stats:
        description: Shows Quest Stats Of The Player
        default: true
        children:
            qquests.stats.sign: true
    qquests.create.sign:
        description: Lets players create qQuests signs
        default: op
    qquests.destroy.sign:
        description: Lets players destroy qQuests signs
        default: op
    qquests.admin:
        description: Lets players edit things like signs, and other dangerous things
        default: true
        children:
            qquests.admin.sign: true
            qquests.create.sign: true
            qquests.destroy.sign: true
    qquests.reload:
        description: Reloads qQuests
        default: op
        children:
            qquests.reload.sign: true
