name: qQuests
main: me.quaz3l.qQuests.qQuests
version: 0.01.92
description: A overly customizable quests plugin.
softdepend: [Vault]
commands:
  Q:
    description: Alias Command To Use qQuests
  QUEST:
    description: Main Command To Use qQuests
  QUESTS:
    description: Alias Command To Use qQuests
  QQUESTS:
    description: Alternate Command To Use qQuests (Just In-Case)
permissions:
    qquests.*:
        description: Gives all qQuest permissions
        default: op
        children:
            qquests.give: true
            qquests.give.specific: true
            qquests.info: true
            qquests.tasks: true
            qquests.drop: true
            qquests.done: true
    qquests.give:
        description: Lets players randomly get a visible quest
        default: true
    qquests.give.specific:
        description: Lets players specify a quest they want
        default: op
    qquests.info:
        description: Lets players see info on there quest
        default: true
    qquests.tasks:
        description: Lets players see there tasks
        default: true
    qquests.drop:
        description: Enables players to drop quests
        default: true
    qquests.done:
        description: Lets players finish a quest
        default: true
